"""add user_id foreign key to account tables

Revision ID: 467c7a6f94a3
Revises: ae03be5cc45c
Create Date: 2026-05-06 10:11:18.683408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467c7a6f94a3'
down_revision: Union[str, Sequence[str], None] = 'ae03be5cc45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_accounts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'current_accounts', 'users', ['user_id'], ['id'])
    op.add_column('savings_accounts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'savings_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings_accounts', type_='foreignkey')
    op.drop_column('savings_accounts', 'user_id')
    op.drop_constraint(None, 'current_accounts', type_='foreignkey')
    op.drop_column('current_accounts', 'user_id')
    # ### end Alembic commands ###
