"""create accounts tables

Revision ID: 9906973a61e8
Revises: 
Create Date: 2026-05-03 14:51:24.246651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9906973a61e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_accounts',
    sa.Column('account_holder', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('overdraft_limit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('account_number')
    )
    op.create_table('savings_accounts',
    sa.Column('account_holder', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('interest_strategy', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('account_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_accounts')
    op.drop_table('current_accounts')
    # ### end Alembic commands ###
