"""change float columns to numeric

Revision ID: 9dd624ec0e89
Revises: 467c7a6f94a3
Create Date: 2026-06-10 17:03:02.768585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd624ec0e89'
down_revision: Union[str, Sequence[str], None] = '467c7a6f94a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_accounts', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('current_accounts', 'overdraft_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('savings_accounts', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('savings_accounts', 'interest_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_accounts', 'interest_rate',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('savings_accounts', 'balance',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('current_accounts', 'overdraft_limit',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('current_accounts', 'balance',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
